# Generated by Django 4.0.6 on 2022-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauth', '0002_alter_telegramuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='link',
            field=models.URLField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
